global:
  message: Welcome to customer service Dev Environment
server:
  port: 8082
message: Hello From Dev !!!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cust_dev
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
